theme: jekyll-theme-minimal
title: <font color="fuchsia"> Hi!</font>
description: <p style="font-size:30px"><b><font color="fuchsia">I'm Alejandra Berbesi</font>&#127774;</b></p>
 <p><b>I enjoy creating predictive models &#128302;</b></p>
 <p><b>I &#128156; ML and i'm learning about DL</b></p>
 <p><b> Main PL -->Python &#128013;</b></p>
 <p><a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/" style="color:fuchsia">Add me in linkedin</a></p>

plugins:
  - jemoji
