theme: jekyll-theme-minimal

title: <font color="MEDIUMORCHID"> Welcome to my portfolio! </font>
description: <p style="font-size:15px"><b> Im Ale Berbesi and here you can find my personal projects&#10145;<br>
I do them mostly for fun and to keep learning<br>
Python is my main programming language. </b></p>
 <p><b><a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/" style="color:MEDIUMORCHID"> Want to chat? Just add me in linkedin! </a></b></p>

plugins:
  - jemoji
