theme: jekyll-theme-cayman
title: Welcome to my portfolio!
description: My name is Alejandra Berbesi. I'm a colombian Data Scientist. I love online learning and in this page you can find the projects im currently working on.
