theme: jekyll-theme-minimal
title: <font color="MEDIUMORCHID"> Hi!&#127797;</font>
description: <p style="font-size:20px"><b><font color="MEDIUMORCHID">I'm Alejandra Berbesi</font></b></p>
 <p><b>I enjoy creating predictive models &#128302;</b></p>
 <p><b>I &#128156; ML and i'm learning about DL</b></p>
 <p><b> Main PL -->Python &#128013;</b></p>
 <p><a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/" style="color:MEDIUMORCHID">Add me in linkedin</a></p>

plugins:
  - jemoji
