theme: jekyll-theme-minimal
title: <font color="LIGHTSTEELBLUE"> Hi! </font>
description: <p> My name is Alejandra Berbesi. I'm a colombian Data Scientist. 
 I love interesting machine learning applications and i'm trying to enter the deep learning and AI world. 
 My main programming language for projects is Python.</p>
 <p> If you want to know more professional facts about me, add me in <a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/">linkedin</a>.</p> 
 <p><b><font color="LIGHTSTEELBLUE"> I hope you like my page...have a great day! </font></b></p>

plugins:
  - jemoji
