theme: jekyll-theme-minimal
title: <font color="purple"> Hi!</font>
description: <p><b><font color="purple">I'm Alejandra Berbesi :sun_with_face: </font></p></b>
 <p><b>I enjoy creating predictive models:crystal_ball:</b></p>
 <p><b>I love ML and i'm learning about DL </b></p>
 <p><b> Main PL -->Python :snake:</b></p>
 <p><a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/" style="color:blue">Add me in linkedin</a></p>

plugins:
  - jemoji
