theme: jekyll-theme-minimal
title: <font color="fuchsia"> Hi!</font>
description: <p><b><font color="fuchsia">I'm Alejandra Berbesi :sun_with_face: </font></p></b>
 <p><b>I enjoy creating predictive models &#128302;</b></p>
 <p><b>I &#128156; ML and i'm learning about DL</b></p>
 <p><b> Main PL -->Python :snake:</b></p>
 <p><a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/" style="color:fuchsia">Add me in linkedin</a></p>

plugins:
  - jemoji
