theme: jekyll-theme-minimal
title: <font color="FUCHSIA"> Hi!</font>
description: <p><b><font color="FUCHSIA">I'm Alejandra Berbesi </font></p></b>
  <p><b>I enjoy using machine learning & deep learning to create predictive models:crystal_ball:</b></p>
 <p><b> Main PL -->Python :snake:</b></p>
 <p><b><a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/" style="color:FUCHSIA">Add me in linkedin</a></b></p>

plugins:
  - jemoji
