theme: jekyll-theme-minimal
title: <font color="FUCHSIA"> Hi! I'm Alejandra B.</font>
description: <p><b>I enjoy using machine learning & deep learning to create predictive models.</b></p>
 <p><b> Main programming language:Python :snake:</b></p>
 <p><b><a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/" style="color:FUCHSIA">Add me in linkedin</a></b></p>

plugins:
  - jemoji
