theme: jekyll-theme-minimal

title: <font color="MEDIUMORCHID"> Welcome to my portfolio! </font>
description: <p style="font-size:20px"><b><font color="MEDIUMORCHID">I'm Ale Berbesi. I live in Colombia &#127758;...Here you can find my personal projects classified
according to the subject. I do them mostly for fun and to keep learning </font></b></p>
 <p><b> Python is my main programming language &#128013; </b></p>
 <p><b><a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/" style="color:MEDIUMORCHID"> Want to chat? Just add me in linkedin! </a></b></p>

plugins:
  - jemoji
