theme: jekyll-theme-minimal
title: <font color="CADETBLUE"> Hi! </font>
description: <p> My name is Alejandra Berbesi. 
 I am a Data Scientist. 
 I enjoy using machine learning and deep learning to create predictive models. 
 My main programming language is Python.</p>
 <p><b><font color="CADETBLUE"> If you want to know more about me, add me in <a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/">linkedin</a>.</font></b></p>

plugins:
  - jemoji
