remote_theme: pages-themes/minimal@v0.2.0

# title: <font color="MEDIUMORCHID"> Hi!&#127797;</font>
# description: <p style="font-size:20px"><b><font color="MEDIUMORCHID">I'm Alejandra Berbesi</font></b></p>
#  <p><b>I love learning new technologies. I'm interested in education projects & tech for good causes &#129429</b></p>
#  <p><b><a href="https://www.linkedin.com/in/alejandra-berbesi-becerra/" style="color:MEDIUMORCHID">Add me in linkedin</a></b></p>

plugins: 
- jekyll-remote-theme
